CSEC-18899 bumping goreleaser-action from 3 to 3.2
coveooss/tgf pull request #389
Opened 2023-01-17 19:03 UTC by cyb3rjerry

Bumping goreleaser-action from 3 to 3.2 via hash to comply with CSEC's GHA policy

2023-01-18 10:45 UTC, JHeilCoveo approved these changes

2023-01-18 11:57 UTC, jonapich requested changes
Action is not allowed

2023-01-18 14:25 UTC, cyb3rjerry commented
Fixed, sorry for the trouble

2023-01-23 12:14 UTC, jonapich approved these changes

2023-01-23 12:14 UTC, merged